services:

#ToDo: setup secure credentials for prod
  fcm_db:
    image: mariadb:latest

    restart: always

    container_name: fcm_db

    env_file: "db.env"

    volumes:
      - fcm_db_data:/var/lib/mysql
    
    healthcheck:
      test: ["CMD-SHELL", "true"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s

    networks:
      - api_db

  fcm_api:
    build: ./api
    environment:
      - APP_NAME=fcm_api
    env_file: "api.env"
    container_name: fcm_api
    restart: always    
    depends_on:
      fcm_db:
        condition: service_healthy

    volumes:
      - fcm_file_exchange:/file_exchange # public

    networks:
      - web_api
      - api_db

  fcm_webserver:
    build: ./frontendVite
    container_name: fcm_webserver
    restart: always    
    depends_on:
      - fcm_api
    networks:
      - web_api
      - frontend
    volumes:
      - fcm_file_exchange:/file_exchange # public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fcm_webserver.rule=Host(`finance-center-meier.com`)"
      - "traefik.http.routers.fcm_webserver.entrypoints=websecure"
      - "traefik.http.routers.fcm_webserver.tls.certresolver=letsencrypt"

  traefik:
    image: traefik:3.6
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
    command:
      - "--configFile=/traefik.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`finance-center-meier.com`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
    networks:
      - frontend


volumes:
  fcm_db_data:
  fcm_file_exchange: # public !!!

networks:
  api_db:
  web_api:
  frontend: