services:
  fcm_db:
    image: mariadb:12.1.2-noble

    restart: always

    container_name: fcm_db

    env_file: "db.env"

    volumes:
      - fcm_db_data:/var/lib/mysql
    
    healthcheck:
      test: ["CMD-SHELL", "true"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s

    networks:
      - api_db

  fcm_api:
    build: ./api
    environment:
      - APP_NAME=fcm_api
    env_file: "api.env"
    container_name: fcm_api
    restart: always    
    depends_on:
      fcm_db:
        condition: service_healthy

    volumes:
      - fcm_file_exchange:/file_exchange # public

    networks:
      - web_api
      - api_db

  fcm_webserver:
    build: ./frontendVite
    container_name: fcm_webserver
    restart: always    
    depends_on:
      - fcm_api
    networks:
      - web_api
      - frontend
    volumes:
      - fcm_file_exchange:/file_exchange # public
    labels:
      - "traefik.enable=true"

      #HTTP router(needed for ACME)
      - "traefik.http.routers.fcm_webserver_http.rule=Host(`192.168.2.229`)"
      - "traefik.http.routers.fcm_webserver_http.entrypoints=web"
      - "traefik.http.routers.fcm_webserver_http.middlewares=redirect-to-https"

      #HTTPS router
      - "traefik.http.routers.fcm_webserver_https.rule=Host(`192.168.2.229`)"
      - "traefik.http.routers.fcm_webserver_https.entrypoints=websecure"
      - "traefik.http.routers.fcm_webserver_https.tls.certresolver=letsencrypt"
      - "traefik.http.services.fcm_webserver.loadbalancer.server.port=80"

  traefik:
    image: traefik:3.6
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
    command:
      - "--configFile=/traefik.yml"
    networks:
      - frontend


volumes:
  fcm_db_data:
  fcm_file_exchange:

networks:
  api_db:
  web_api:
  frontend: