const Infrastruktur = () => {
    return (
        <>
            <h2 className="text-4xl text-center text-[#093B3F] font-bold md:mb-10 md:mt-10">Moderne Infrastruktur und Einrichtungen</h2>
            <p className="md:ml-50 md:mr-50 max-md:ml-10 max-md:mr-10 text-[#093B3F] text-justify text-lg">Zypern verfügt über eine hervorragend ausgebaute Infrastruktur. Neue Schnellstraßen verbinden die Ost- und Westküste und ermöglichen eine bequeme Erkundung der Insel. Die modernen Straßen machen es einfach, schnell von einer Region in die andere zu gelangen, sei es für den täglichen Pendelverkehr oder für Ausflüge zu den vielen Sehenswürdigkeiten der Insel.</p>
            <p className="md:ml-50 md:mr-50 max-md:ml-10 max-md:mr-10 text-[#093B3F] text-justify text-lg">Die Karpaz Gate Marina ist ein luxuriöser Yachthafen, der internationale Segler anzieht. Dieser hochmoderne Hafen bietet erstklassige Einrichtungen und Dienstleistungen für Bootsbesitzer und ist ein beliebter Anlaufpunkt für Yacht-Touristen aus der ganzen Welt. Mit seinen hochwertigen Restaurants, exklusiven Boutiquen und umfangreichen Freizeitmöglichkeiten ist die Karpaz Gate Marina ein Zentrum für maritime Aktivitäten und luxuriösen Lebensstil.</p>
            <p className="md:ml-50 md:mr-50 max-md:ml-10 max-md:mr-10 text-[#093B3F] text-justify text-lg">Das Near East University Hospital zählt zu den führenden medizinischen Einrichtungen in der Region und bietet erstklassige Versorgung, insbesondere in den Bereichen Herz- und Krebserkrankungen. Dieses hochmoderne Krankenhaus ist mit modernster Technologie ausgestattet und zieht Patienten aus der ganzen Welt an, die hier erstklassige medizinische Betreuung erhalten. Das Fachpersonal und die spezialisierten Ärzte gewährleisten eine hochwertige Gesundheitsversorgung, die international anerkannt ist.</p>
            <p className="md:ml-50 md:mr-50 max-md:ml-10 max-md:mr-10 text-[#093B3F] text-justify text-lg">Die Near East Universität und andere renommierte Bildungseinrichtungen auf Zypern ziehen Studierende aus der ganzen Welt an. Diese Universitäten bieten eine breite Palette von Studiengängen und eine qualitativ hochwertige Ausbildung, die international anerkannt ist. Die multikulturelle Atmosphäre auf den Campus-Geländen fördert den Austausch von Wissen und kultureller Vielfalt, was das Studium auf Zypern zu einer bereichernden Erfahrung macht.</p>
            <p className="md:ml-50 md:mr-50 max-md:ml-10 max-md:mr-10 text-[#093B3F] text-justify text-lg">Darüber hinaus verfügt Zypern über gut entwickelte öffentliche und private Verkehrssysteme, die eine einfache Mobilität auf der Insel ermöglichen. Der internationale Flughafen in Larnaca und der Flughafen in Paphos verbinden Zypern mit vielen Städten weltweit, was die Anreise für internationale Besucher und Geschäftsreisende erleichtert.</p>
            <p className="md:ml-50 md:mr-50 max-md:ml-10 max-md:mr-10 text-[#093B3F] text-justify text-lg">Die umfassende Infrastruktur auf Zypern trägt erheblich zur Lebensqualität bei und macht die Insel zu einem attraktiven Ort zum Leben, Studieren und Arbeiten. Ob Sie die Insel erkunden, eine erstklassige medizinische Versorgung benötigen oder eine hochwertige Ausbildung suchen, Zypern bietet alles, was Sie brauchen, um ein komfortables und erfülltes Leben zu führen.</p>
        
        </>
    )
}

export default Infrastruktur;