export interface CreateImmoDto {
    objectnr: number,
    city_de?: string,
    city_en?: string,
    city_ru?: string,
    description_de?: string,
    description_en?: string,
    description_ru?: string,
    house?: boolean,
    price?: number,
    squareMeters?: number,
    bathroom?: boolean,
    supermarket?: boolean,
    electricity?: boolean,
    water?: boolean,
    pool?: boolean,
    garden?: boolean,
    atOcean?: boolean,
    paymentDuration?: number,
    buildingFinished?: string,
    uberDasProjekt_de?: string,
    uberDasProjekt_en?: string,
    uberDasProjekt_ru?: string,
    uberStandort_de?: string,
    uberStandort_en?: string,
    uberStandort_ru?: string,
    carouselObject?: boolean
}