name: Automatic Server Deployment

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Build the Docker image
      run: | 
        docker build . --file ./api/Dockerfile --tag fcm_api:${{ github.ref_name }}
        docker build . --file ./frontendVite/Dockerfile --tag fcm_webserver:${{ github.ref_name }} 