name: Automatic Server Deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get latest git tag
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo "VERSION=$TAG" >> $GITHUB_ENV

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | \
        docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker images
      run: |
        docker build ./api \
          --file ./api/Dockerfile \
          --tag ${{ secrets.DOCKER_HUB_USERNAME }}/fcm_api:${VERSION}

        docker build ./frontendVite \
          --file ./frontendVite/Dockerfile \
          --tag ${{ secrets.DOCKER_HUB_USERNAME }}/fcm_webserver:${VERSION}

    - name: Push Docker images
      run: |
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/fcm_api:${VERSION} ${{ secrets.DOCKER_HUB_USERNAME }}/fcm_api:latest
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/fcm_webserver:${VERSION} ${{ secrets.DOCKER_HUB_USERNAME }}/fcm_webserver:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fcm_api:${VERSION}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fcm_webserver:${VERSION}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fcm_api:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fcm_webserver:latest
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP_ADDRESS }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        script: |
          cd /home/prod/realprod

          cat > db.env <<EOF
          # .env

          MARIADB_ROOT_PASSWORD=${{ secrets.MARIADB_ROOT_PASSWORD }}
          MARIADB_DATABASE=${{ secrets.MARIADB_DATABASE }}
          MARIADB_USER=${{ secrets.MARIADB_USER }}
          MARIADB_PASSWORD=${{ secrets.MARIADB_PASSWORD }}
          EOF

          cat > api.env <<EOF
          # .env

          DB_NAME=${{ secrets.MARIADB_DATABASE }}
          DB_USER=${{ secrets.MARIADB_USER }}
          DB_PASS=${{ secrets.MARIADB_PASSWORD }}
          DB_HOST=fcm_db
          DB_PORT=3306
          ADMIN_PASS=${{ secrets.ADMIN_PASS }}
          ADMIN_NAME=${{ secrets.ADMIN_NAME }}
          JWT_TOKEN=${{ secrets.JWT_TOKEN }}
          EOF

          docker-compose pull
          docker-compose up -d --force-recreate --build
